use_frameworks!

target 'YXBPhotoBrowser_Example' do
  pod 'YXBPhotoBrowser', :path => '../'
  pod 'Reveal-SDK','~>4', :configurations => ['Debug']
  target 'YXBPhotoBrowser_Tests' do
    inherit! :search_paths

    
  end
end
